#! /bin/bash

#installer
if [[ $1 == "-i" ]]; then
sudo apt-get install $2
fi

#updater
if [[ $1 == "-u" ]]; then
sudo apt-get update
fi

#upgrade
if [[ $1 == "-U" ]]; then
sudo apt-get upgrade
fi

#fix missing packages if needed
if [[ $1 == "-f" ]]; then
sudo apt-get update --fix-missing
fi

#display help
if [[ $1 == "-h" ]];then
echo -e "-i <package> - Installs packages"
echo -e "-u - Updates packages"
echo -e "-U - Upgrades packages (case sensitive)"
echo -e "-f - Fixes missing packages"
echo -e "-h - Shows this help"
fi
